### PR TITLE
fix: show proper name, and relabel numbers

### LINKED ISSUE #85: Names of options not updated after ordering by indexes in OutcomesInfo
Everything else does update (image, link...)

Also why are we renderring those `#1` numbers, do they provide any information at all? It's weird to see those numbers out of order

image

### PR DESCRIPTION
**Pull request by greenlucid**
closes #85

### CODE REVIEW

**Comment by nvm1410** [comment]
this will not work probably since outcomes array is already sliced

**Comment by greenlucid** [comment]
Not sure I follow, when will this break? It works on my machine @nvm1410
Had to change the outcome we access, because since we're overwriting the indexes we're accessing (from the `j` ordering to the `i` ordering), it will be wrong to not overwrite the `outcome` or the `wrappedAddress` as well

**Comment by nvm1410** [comment]
Screenshot 2024-10-10 233558

**Comment by nvm1410** [comment]
Because the array is sliced before sorting, the outcome may not be there after sort

**Comment by xyzseer** [comment]
fixed on 7d6f7dbfe85f9ce8eaf2217d41856dd7930fb6df

**Comment by greenlucid** [comment]
you missed something I also tackled here (the wrappedAddress in Outcomes) but making the PR for that using the same strategy of accessing the array
https://github.com/seer-pm/demo/pull/89

**Pull request closed without merging**
